[projects]
[projects."/tmp/tmp.SDF2HBbOWL"]
trust_level = "trusted"

[projects."/mnt/a/dev/grimforge-site"]
trust_level = "trusted"

[mcp_servers]
[mcp_servers.context7-mcp]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@upstash/context7-mcp", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8" ]

[mcp_servers.desktop-commander]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@wonderwhy-er/desktop-commander", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8" ]

[mcp_servers.n8n-mcp]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@vincentmcleese/n8n-mcp", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8", "--profile", "physical-seahorse-rSkSJ9" ]

[mcp_servers.supabase-mcp]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@supabase-community/supabase-mcp", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8", "--profile", "physical-seahorse-rSkSJ9" ]

[mcp_servers.mcp-browserbase]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@browserbasehq/mcp-browserbase", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8", "--profile", "physical-seahorse-rSkSJ9" ]

[mcp_servers.mcp-server]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@hugeicons/mcp-server", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8" ]

[mcp_servers.toolbox]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@smithery/toolbox", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8", "--profile", "physical-seahorse-rSkSJ9" ]

[mcp_servers.openapi-mcp-server]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@janwilmake/openapi-mcp-server", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8" ]

[mcp_servers.puppeteer]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@smithery-ai/puppeteer", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8" ]

[mcp_servers.memory-palace-mcp]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@zeyynepkaraduman/memory-palace-mcp", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8" ]

[mcp_servers.reference-servers]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@kiennd/reference-servers", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8" ]

[mcp_servers.super-shell-mcp]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@cfdude/super-shell-mcp", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8" ]

[mcp_servers.mcp-neo4j-agent-memory]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@knowall-ai/mcp-neo4j-agent-memory", "--key", "1d981d55-c8e2-40d7-952b-b26e4f8fd8d8", "--profile", "physical-seahorse-rSkSJ9" ]