// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shbalyvvquvtvnkrsxtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoYmFseXZ2cXV2dHZua3JzeHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDY4MzgsImV4cCI6MjA3MDMyMjgzOH0.oeI0CLImpKIRjp1cZ8u53cNLWQrTtnTGTKy5Zi6MaXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});